server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
server/src/main/java/backend/section6mainproject/member/service/MemberService.java
server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDto.java
server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceTest.java

Feat: WalkLog Petch 기능 구현 , WalkLogStatus 추가
Test: WalkLog Petch Test 구현
Formatting: MemberMapper 메서드명 카멜케이스 수정

Feat: WalkLog petch 기능 구현 및 테스트 작성 (#18)

---

client/src/components/OnWalk/Camera.module.scss
client/src/components/OnWalk/Camera.tsx
client/src/components/OnWalk/ImgInput.module.scss
client/src/components/OnWalk/ImgInput.tsx
client/src/components/OnWalk/SnapForm.module.scss
client/src/components/OnWalk/SnapForm.tsx
client/src/pages/OnWalk.tsx

[FE] Feat: 걷는 중 순간 기록 페이지 구현

---

client/package-lock.json
client/package.json
client/src/components/common/Map.module.scss
client/src/components/common/Map.tsx
client/src/pages/Home.tsx
client/src/router/index.tsx

[FE] 맵 컴포넌트 구현

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/apis/user.ts
client/src/components/common/Map.module.scss
client/src/hooks/useRouter.ts
client/src/pages/Home.tsx
client/src/pages/SignIn.module.scss
client/src/pages/SignIn.tsx
client/src/pages/SignUp.module.scss
client/src/pages/SignUp.tsx
client/src/store/authAtom.ts
client/src/store/userAtom.ts
client/src/utils/refreshTokenHandler.ts
client/vite.config.ts

- 회원가입
- 로그인
- access token, refresh token 관리
- path 이동 시 로그인 여부 체크
todo
- email, 비밀번호 유효성 검사

[FE] Feat: SingIn, SingUp 기능 구현

---

server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentControllerDTO.java
server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
server/src/main/java/backend/section6mainproject/coordinate/interceptor/SubscribeInterceptor.java
server/src/main/java/backend/section6mainproject/exception/BusinessLogicException.java

```java
2023-05-17 11:38:52.012  INFO 22128 --- [nio-8080-exec-4] b.s.exception.BusinessLogicException     : exception code : WALK_LOG_NOT_FOUND, attributes : {dest=/sub/1, requiredId=2}
```
이런식으로 로그가 찍히게 됩니다.

Refactor: 비즈니스 로직 예외 발생시 로깅 추가 (#125)

---

client/package-lock.json
client/package.json
client/src/components/HistoryList/Calendar/Calendar.module.scss
client/src/components/HistoryList/Calendar/Calendar.tsx
client/src/components/HistoryList/Calendar/Dates.module.scss
client/src/components/HistoryList/Calendar/Dates.tsx
client/src/components/HistoryList/Calendar/WeekDays.module.scss
client/src/components/HistoryList/Calendar/WeekDays.tsx
client/src/components/HistoryList/Calendar/YearMonth.tsx
client/src/components/HistoryList/Calendar/date-fns.ts
client/src/components/HistoryList/History.tsx
client/src/components/HistoryList/HistoryItem.tsx
client/src/components/HistoryList/Toggle.module.scss
client/src/components/HistoryList/Toggle.tsx
client/src/components/OnWalk/Camera.tsx
client/src/components/OnWalk/SnapForm.tsx
client/src/components/common/Icon.tsx
client/src/components/common/Map.tsx
client/src/components/common/Modal.tsx
client/src/pages/HistoryList.module.scss
client/src/pages/HistoryList.tsx

달력 Date 객체에서 라이브러리(date-fns)로 변경
TypeScript 협의했던 컨벤션에 맞게 변경 (Interface → Type)
날짜 선택 기능 추가
- 선택된 날짜에 원 테두리 표시

[FE] Refactor: 기록리스트 & 달력 컴포넌츠 리팩토링

---

client/src/apis/user.ts
client/src/pages/SignUp.tsx

[FE] Fix: 로그인 실패 시에도 성공으로 인식되는 이슈 해결

---

server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java

Fix: 걷기 종료시 순간기록이 없으면 종료가 안되는 문제 수정 (#179)

---

client/src/pages/SignUp.tsx

[FE] Feat: 이메일 유효성 검증 방식 변경

---

client/src/apis/user.ts
client/src/components/FindPassword/TempPasswordSent.module.scss
client/src/components/FindPassword/TempPasswordSent.tsx
client/src/pages/FindPassword.module.scss
client/src/pages/FindPassword.tsx
client/src/pages/SignIn.tsx
client/src/pages/SignUp.tsx
client/src/router/routerData.tsx
client/vite.config.ts

[FE] Feat: 비밀번호 찾기 기능

---

server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
server/src/main/java/backend/section6mainproject/member/service/MemberService.java
server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
server/src/test/java/backend/section6mainproject/member/MemberStubData.java
server/src/test/java/backend/section6mainproject/member/service/MemberServiceTest.java
server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java

로그아웃 API : POST /members/logout

[BE] 로그아웃 기능 구현

---

client/src/apis/user.ts
client/src/pages/MyPage.tsx
client/vite.config.ts

- 회원탈퇴 기능 구현
- 비로그인 시 로그인 페이지로 리다이렉트

[FE] Feat: 회원 탈퇴 기능

---

client/package-lock.json
client/package.json
client/src/components/common/Header.module.scss
client/src/components/common/Header.tsx
client/src/pages/ChangePassword.tsx
client/src/pages/FindPassword.tsx
client/src/pages/HistoryDetail.tsx
client/src/pages/SignIn.tsx
client/src/pages/SignUp.tsx
client/vite.config.ts

- 헤더 컴포넌트 구현
- SignIn, SignUp, ChangePassword, FindPassword, HistoryDetail에 적용

[FE] Feat: 헤더 컴포넌트

---

client/.env.development
client/.env.production
client/.gitignore
client/src/apis/user.ts
client/src/components/ChangePassword/ChangingPassword.tsx
client/src/components/MyPage/EditProfile.tsx
client/src/components/common/Header.tsx
client/src/layout/GeneralLayout.tsx
client/src/pages/FindPassword.tsx
client/src/pages/HistoryDetail.tsx
client/src/pages/MyPage.tsx
client/src/pages/SignIn.tsx

- `/api` 제거
- 기존 컴포넌트에서 인자로 url을 넣던 방식에서, user.ts 에서 url을 직접 입력하는 방식으로 변경

[FE] Refactor: user 요청 URL 변경

---

server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java

현재 이미지를 안보내면 null값으로 변경되는 문제는 수정되었으나 MultipartFile란에 이름만 넣고 빈값을 보내는 경우는 이미지 파일이 null으로 변경됩니다. 
괜찮을지 의견도 같이 여쭤보고싶습니다

217 be 수정 요청시 기존 이미지파일이 삭제되는 문제 해결

---

client/src/components/HistoryDetail/Title.tsx
client/src/components/MyPage/EditProfile.tsx
client/src/layout/GeneralLayout.tsx
client/src/pages/MyPage.tsx
client/src/pages/SignIn.tsx

Fix: 빌드 시도 시 오류나는 부분 해결하기 (#230)

---

server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java

Fix:걷기 종료시 mapImage가 정상적으로 저장되지 않는 현상 수정 (#237)

---

server/src/main/java/backend/section6mainproject/TestDataInit.java
server/src/main/java/backend/section6mainproject/advice/MemberVerifyAdvice.java
server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
server/src/main/java/backend/section6mainproject/walklog/controller/AnonymousWalkLogController.java
server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogService.java
server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogServiceImpl.java
server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java

TestDataInit은 테스트 용도로만 필요하다고 판단해서 `@Component`를 주석처리 했습니다.

[BE] 비회원 걷기 기록 종료

---

client/src/apis/walkLog.ts
client/src/assets/search-light.svg
client/src/assets/sprite-icon.svg
client/src/components/Feed/FeedItem.module.scss
client/src/components/Feed/FeedItem.tsx
client/src/components/Feed/SnapItem.module.scss
client/src/components/Feed/SnapItem.tsx
client/src/components/HistoryList/History.tsx
client/src/components/common/Icon.tsx
client/src/pages/Feed.module.scss
client/src/pages/Feed.tsx
client/src/utils/date-fns.ts
client/src/utils/date.ts

- 피드 컴포넌트 레이아웃
- 데이터 배치
- 무한 스크롤
todo
- 리전 데이터 연결

[FE] Feat: 피드 컴포넌트 구현

---

client/src/apis/user.ts
client/src/pages/MyPage.module.scss
client/src/pages/MyPage.tsx
client/vite.config.ts

- 모달로 로그아웃 의사 확인
- 로그아웃 시 axiosInstance default header의 `Authorization` 제거

[FE] Feat: 로그아웃 기능 구현

---

client/src/components/MyPage/EditProfile.tsx
client/src/components/MyPage/ProfileImgInput.tsx
client/src/pages/MyPage.module.scss
client/src/pages/MyPage.tsx
client/vite.config.ts

[FE] Fix: 마이페이지 버그 수정

---

client/src/components/HistoryDetail/Title.module.scss
client/src/components/HistoryDetail/Title.tsx
client/src/pages/HistoryDetail.tsx

작성자 외 유저가 걷기 기록 1건 조회시 상단에 작성자 프로필 이미지와 닉네임 조회

[FE] Design: 작성자 외 유저가 걷기 기록 조회시 작성자 조회 (#252)

---

client/src/apis/user.ts
client/src/components/MyPage/EditProfile.tsx
client/src/pages/MyPage.tsx
client/src/pages/SignIn.tsx
client/src/pages/SignUp.tsx
client/vite.config.ts

[FE] Fix: 배포 시 발생하는 버그 수정

---

client/src/apis/snap.ts
client/src/components/common/ImgInput.tsx
client/src/components/common/Item/SnapItem.tsx
client/src/components/common/Modal.module.scss
client/src/components/common/Modal.tsx
client/src/components/common/SnapForm.module.scss
client/src/components/common/SnapForm.tsx
client/src/pages/OnWalk.module.scss
client/src/pages/OnWalk.tsx

OnWalk 페이지에서 순간기록 등록, 수정, 삭제 기능 구현

[FE] Feat: OnWalk 페이지 순간기록 수정/삭제

---

client/src/components/common/Tapbar.module.scss

[FE] Test: 홈 바 safe-area-test

---

client/src/pages/SignIn.tsx
vercel.json

[FE] Fix:  주소창에 경로 입력해서 접속시 404 오류

---

client/src/components/common/Tapbar.module.scss
client/src/components/common/Tapbar.tsx

[FE] Design: 탭바 요소 가운데 정렬

---

client/src/components/Feed/FeedItem.tsx
client/src/components/Feed/SnapItem.tsx
client/src/components/HistoryList/History.module.scss
client/src/components/HistoryList/History.tsx
client/src/components/HistoryList/HistoryItem.module.scss
client/src/components/HistoryList/HistoryItem.tsx
client/src/pages/HistoryDetail.tsx
client/src/pages/HistoryList.module.scss
client/src/pages/HistoryList.tsx

- 기록 리스트에 기록이 하나도 없을 때 시작 제안하는 문구 조회
- 기록리스트에서 사진 있는 / 없는순간 기록들 배열 맞추기
- 기록리스트, 기록 상세, 피드에서 순간기록의 시간표시를 타이머가 아닌 작성 시간포맷으로 바꾸기

[FE] Design 기록 리스트, 순간기록 디자인, 리팩토링

---

client/src/components/Feed/SnapItem.module.scss
client/src/components/Feed/SnapItem.tsx
client/src/pages/HistoryDetail.tsx
client/src/pages/HistoryList.tsx

이미지 없는 순간 기록 noimage 아이콘 넣기
기록 한 개도 없을 때 기록 남겨보라는 메세지가 나오는데, 달력 토글 열었을 때에는 메세지 숨김

[FE] Design: 이미지 없는 순간 기록 noimage 아이콘 넣기

---

client/src/App.tsx
client/src/components/HistoryDetail/DetailItem.tsx
client/src/main.tsx
client/src/pages/HistoryDetail.tsx

google map api와의 충돌문제여서 google map provider와 queryClientProvider를 분리

[FE] Fix: 순간 기록 수정 삭제 바로 반영 안되는 문제

---

client/src/components/Feed/FeedItem.module.scss
client/src/components/Feed/FeedItem.tsx
client/src/components/Feed/SnapItem.module.scss
client/src/components/HistoryList/History.module.scss
client/src/components/HistoryList/History.tsx
client/src/components/header/HomeHeader.tsx
client/src/pages/Feed.tsx
client/src/pages/HistoryList.module.scss
client/src/router/routerData.tsx

비로그인시 피드에서 기록 상세페이지 접근 가능하게 변경
디자인 기록리스트와 맞추기

[FE] Feat: 피드의 기록 상세페이지 로그인 없이 접근 가능하게 변경 & 디자인 추가

---

client/src/components/Home/PwaCarousel.module.scss
client/src/components/Home/PwaCarousel.tsx
client/src/pages/Home.tsx
client/src/types/Carousel.ts
client/src/utils/date-fns.ts

안드로이드, ios 나눠서 PWA 로 홈화면에 앱 추가하는 방법 모달 캐러셀로 보여줌

[FE] Feat: pwa 사용법 팝업창 만들기

---

client/index.html
client/package-lock.json
client/package.json
client/src/components/common/Map/StaticPathMap.tsx
client/src/pages/AfterWalk.module.scss
client/src/pages/AfterWalk.tsx
client/src/pages/HistoryDetail.tsx
client/src/pages/OnWalk.tsx

- sockjs 로 https로 요청
- content header에 엑세스토큰 담아서 보냄
- /sub/{walklogId} => 전송 내역 수신
- /pub/walk-log => 경로 전송

[FE] Feat: 실시간 좌표 웹소켓으로 서버 전송

---

client/src/components/Home/PwaCarousel.module.scss
client/src/components/Home/PwaCarousel.tsx

- 7일간 보지 않기 버튼 상위로 옮김
- 캐러셀 설명 높이 고정해서 설명이 1줄일 때, 2줄일 때 모두 높이 동일하도록 고정

[FE] Design: PWA 팝업창 디자인 변경 

---

client/src/components/Home/PwaCarousel.module.scss
client/src/components/Home/PwaCarousel.tsx
client/src/components/common/Icon.tsx
client/src/pages/Home.tsx

- 저 좁은 width도 대응하기 위해 양쪽 버튼을 position absolute로 띄워서 가로폭을 더 확보
- 로직을 전부 캐러셀내부로 넣어서, 캐러셀의 렌더링 여부도 캐러셀에서 직접 판단하도록 변경

[FE] Refactor: PWA 캐러셀 리팩토링

---

client/src/components/Home/StartMessage.tsx
client/src/layout/GeneralLayout.tsx
client/src/pages/Home.tsx
client/src/pages/loadingPage/Spinner.module.scss
client/src/pages/loadingPage/Spinner.tsx

걷기 시작하기 클릭 시 랜덤으로 메시지 보여주고 onwalk 페이지로 이동.

[FE] Feat: 걷기 시작 전 메시지 렌더링
